In [13]:
import sys
from pathlib import Path

import pandas as pd

sys.path.append(str(Path.cwd().parent))

from src.data_ingestion import ingest_data

df = ingest_data()

df.head()

Extracting: multilingual-customer-support-tickets.zip
Loading: aa_dataset-tickets-multi-lang-5-2-50-version.csv

Data ingestion completed.
File: aa_dataset-tickets-multi-lang-5-2-50-version.csv
Shape: (28587, 16)

,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte einen gravierenden Sicherheitsvorfall melden, der gegenwärtig mehrere Komponenten unserer Infrastruktur betrifft. Betroffene Geräte umfassen Projektoren, ...",Vielen Dank für die Meldung des kritischen Sicherheitsvorfalls und die Bereitstellung der Übersicht über die betroffenen Geräte sowie der ergriffenen ersten Maßnahmen. Wir erkennen die Dringlichke...,Incident,Technical Support,high,de,51,Security,Outage,Disruption,Data Breach,NaN,NaN,NaN,NaN
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to report a significant problem with the centralized account management portal, which currently appears to be offline. This outage is blocking access to...","Thank you for reaching out, <name>. We are aware of the outage affecting the centralized account management system, and our technical team is actively working to resolve the issue. In the meantime...",Incident,Technical Support,high,en,51,Account,Disruption,Outage,IT,Tech Support,NaN,NaN,NaN
2,Query About Smart Home System Integration Features,"Dear Customer Support Team,\n\nI hope this message reaches you well. I am reaching out to request detailed information about the capabilities of your smart home integration products listed on your...","Thank you for your inquiry. Our products support integration with Amazon Alexa, Google Assistant, and Apple HomeKit. Compatibility details can differ depending on the specific item; please let us ...",Request,Returns and Exchanges,medium,en,51,Product,Feature,Tech Support,NaN,NaN,NaN,NaN,NaN
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this message finds you well. I am reaching out to request clarification about the billing and payment procedures linked to my account. Recently, I observed so...","We appreciate you reaching out with your billing questions. The billing period generally begins on the first day of the month and concludes on the last day, with payments due by the 10th of the fo...",Request,Billing and Payments,low,en,51,Billing,Payment,Account,Documentation,Feedback,NaN,NaN,NaN
4,Question About Marketing Agency Software Compatibility,"Dear Support Team,\n\nI hope this message reaches you well. I am reaching out to ask about the compatibility of your products with the specific needs of marketing agencies. Our company is consider...","Thank you for your inquiry. Our product supports integration with major CRM, email marketing, and analytics platforms through APIs and customization options. Please specify the tools you are using...",Problem,Sales and Pre-Sales,medium,en,51,Product,Feature,Feedback,Tech Support,NaN,NaN,NaN,NaN

In [14]:
df.shape

(28587, 16)

In [15]:
df.columns.tolist()

['subject',
 'body',
 'answer',
 'type',
 'queue',
 'priority',
 'language',
 'version',
 'tag_1',
 'tag_2',
 'tag_3',
 'tag_4',
 'tag_5',
 'tag_6',
 'tag_7',
 'tag_8']

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28587 entries, 0 to 28586
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   subject   24749 non-null  str
 1   body      28587 non-null  str
 2   answer    28580 non-null  str
 3   type      28587 non-null  str
 4   queue     28587 non-null  str
 5   priority  28587 non-null  str
 6   language  28587 non-null  str
 7   version   28587 non-null  int64
 8   tag_1     28587 non-null  str
 9   tag_2     28574 non-null  str
 10  tag_3     28451 non-null  str
 11  tag_4     25529 non-null  str
 12  tag_5     14545 non-null  str
 13  tag_6     5874 non-null   str
 14  tag_7     2040 non-null   str
 15  tag_8     565 non-null    str
dtypes: int64(1), str(15)
memory usage: 27.7 MB

In [17]:
df.isnull().sum()

subject      3838
body            0
answer          7
type            0
queue           0
priority        0
language        0
version         0
tag_1           0
tag_2          13
tag_3         136
tag_4        3058
tag_5       14042
tag_6       22713
tag_7       26547
tag_8       28022
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
subject,24749,24749,Wesentlicher Sicherheitsvorfall,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
body,28587,28587,"Sehr geehrtes Support-Team,\n\nich möchte einen gravierenden Sicherheitsvorfall melden, der gegenwärtig mehrere Komponenten unserer Infrastruktur betrifft. Betroffene Geräte umfassen Projektoren, ...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
answer,28580,28580,Vielen Dank für die Meldung des kritischen Sicherheitsvorfalls und die Bereitstellung der Übersicht über die betroffenen Geräte sowie der ergriffenen ersten Maßnahmen. Wir erkennen die Dringlichke...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
type,28587,4,Incident,11466,NaN,NaN,NaN,NaN,NaN,NaN,NaN
queue,28587,10,Technical Support,8362,NaN,NaN,NaN,NaN,NaN,NaN,NaN
priority,28587,3,medium,11515,NaN,NaN,NaN,NaN,NaN,NaN,NaN
language,28587,2,en,16338,NaN,NaN,NaN,NaN,NaN,NaN,NaN
version,28587.0,NaN,NaN,NaN,278.382027,165.962935,51.0,52.0,400.0,400.0,400.0
tag_1,28587,116,Security,5880,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tag_2,28574,256,Performance,5903,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tag_3,28451,392,IT,6121,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tag_4,25529,554,Tech Support,6568,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tag_5,14545,602,Tech Support,4617,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tag_6,5874,575,Tech Support,1847,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tag_7,2040,427,Tech Support,391,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tag_8,565,224,Tech Support,77,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
for column in ["type","queue","priority","language"]:
    print(f"\n{column}")
    print(df[column].value_counts(dropna=False))

type
type
Incident    11466
Request      8187
Problem      6012
Change       2922
Name: count, dtype: int64

queue
queue
Technical Support                  8362
Product Support                    5252
Customer Service                   4268
IT Support                         3433
Billing and Payments               2788
Returns and Exchanges              1437
Service Outages and Maintenance    1148
Sales and Pre-Sales                 918
Human Resources                     576
General Inquiry                     405
Name: count, dtype: int64

priority
priority
medium    11515
high      11178
low        5894
Name: count, dtype: int64

language
language
en    16338
de    12249
Name: count, dtype: int64

In [21]:
pd.set_option("display.max_colwidth",200)

df[["subject", "body", "type", "queue", "priority", "language"]].head(10)

,subject,body,type,queue,priority,language
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte einen gravierenden Sicherheitsvorfall melden, der gegenwärtig mehrere Komponenten unserer Infrastruktur betrifft. Betroffene Geräte umfassen Projektoren, ...",Incident,Technical Support,high,de
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to report a significant problem with the centralized account management portal, which currently appears to be offline. This outage is blocking access to...",Incident,Technical Support,high,en
2,Query About Smart Home System Integration Features,"Dear Customer Support Team,\n\nI hope this message reaches you well. I am reaching out to request detailed information about the capabilities of your smart home integration products listed on your...",Request,Returns and Exchanges,medium,en
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this message finds you well. I am reaching out to request clarification about the billing and payment procedures linked to my account. Recently, I observed so...",Request,Billing and Payments,low,en
4,Question About Marketing Agency Software Compatibility,"Dear Support Team,\n\nI hope this message reaches you well. I am reaching out to ask about the compatibility of your products with the specific needs of marketing agencies. Our company is consider...",Problem,Sales and Pre-Sales,medium,en
5,Feature Query,"Dear Customer Support,\n\nI hope this message reaches you in good health. I am eager to learn more about the features of one of your products. Would you be able to share comprehensive details abou...",Request,Technical Support,high,en
6,System Interruptions,"Dear Customer Support Team,\n\nI am submitting a report regarding multiple system service disruptions that are currently interfering with project operations and client interactions. These interrup...",Incident,Service Outages and Maintenance,high,en
7,Connectivity Problems with Printer on MacBook Pro,"Dear Support Team,\n\nI am reporting a recurring issue with the Laser Printer when printing from MacBook Pros running macOS 15. Several team members have recently encountered this problem, which a...",Incident,Technical Support,medium,en
8,Anfrage nach detaillierten Angaben zur Systemarchitektur der Plattform,"Sehr geehrtes Kundensupport-Team,\n\nich hoffe, diese Nachricht trifft Sie wohl. Ich nehme Kontakt auf, um umfassende Informationen zur Architektur der Plattform zu erfragen. Das Verständnis der z...",Request,Technical Support,low,de
9,Anfrage zur Klärung der Auswirkungen eines Serviceausfalls,"Sehr geehrtes Kundendienstteam,\n\nich hoffe, diese Nachricht erreicht Sie wohlbehalten. Ich schreibe, um eine Klärung bezüglich des kürzlichen Ausfalls Ihres Dienstes zu bitten, der die Plattform...",Request,Service Outages and Maintenance,high,de

In [22]:
df["subject_length"] = df["subject"].fillna("").str.len()
df["body_length"] = df["body"].fillna("").str.len()

df[["subject_length", "body_length"]].describe()

       subject_length   body_length
count    28587.000000  28587.000000
mean        38.546122    387.263896
std         23.672887    200.129011
min          0.000000      6.000000
25%         27.000000    219.000000
50%         39.000000    386.000000
75%         51.000000    551.000000
max        675.000000   1469.000000

In [23]:
print("Duplicate subjects:", df["subject"].duplicated().sum())
print("Duplicate bodies:", df["body"].duplicated().sum())

Duplicate subjects: 3837
Duplicate bodies: 0

In [24]:
print(df["priority"].value_counts())

priority
medium    11515
high      11178
low        5894
Name: count, dtype: int64

In [25]:
print(df["priority"].value_counts(normalize=True).mul(100).round(2))

priority
medium    40.28
high      39.10
low       20.62
Name: proportion, dtype: float64